CREATE TABLE user (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  nickname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  passwrd VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

CREATE TABLE message (
  id INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  message_date DATETIME NOT NULL,
  message_text TEXT NOT NULL,
  user_id INT(11),
  FOREIGN KEY (user_id) REFERENCES user (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

